// Type declarations for Webpack entry points generated by Electron Forge
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Type declarations for Electron API exposed via preload
interface ElectronAPI {
  togglePanel: () => void;
  getPanelState: () => Promise<boolean>;
}

declare interface Window {
  electronAPI: ElectronAPI;
}
